Description: CFN-Template-Kitchen-Sink -- Root Stack
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  ProviderVPCCidrBlock:
    Type: String
    Description: 'The /16 CIDR block for the Provider VPC (Format Example: 10.0.0.0/16)'
    MinLength: '9'
    MaxLength: '18'
    Default: 10.0.0.0/16
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.0\.0/16
    ConstraintDescription: Must be a valid IP CIDR block with a /16
  ConsumerVPCCidrBlock:
    Type: String
    Description: 'The /16 CIDR block for the Consumer VPC (Format Example: 172.31.0.0/16)'
    MinLength: '9'
    MaxLength: '18'
    Default: 172.31.0.0/16
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.0\.0/16
    ConstraintDescription: Must be a valid IP CIDR block with a /16
  KeyPair:
    Type: AWS::EC2::KeyPair::KeyName
    Description: The name of an Amazon EC2 key pair in the region in which you are
      creating a CloudFormation stack.
    Default: VPC_Break-Fix_Project
  AmazonLinuxAMIVersion:
    Type: String
    Default: AmazonLinuxAMI
    AllowedValues:
      - AmazonLinuxAMI
      - AmazonLinux2AMI
  CaseId:
    Type: Number
    Description: The Case ID for this environment
    MinValue: '4000000000'
    MaxValue: '5000000000'
    Default: '4000000000'
    ConstraintDescription: Must be a valid 10 digit number between 4000000000 and 5000000000
  S3BucketName:
    Type: String
  S3BucketKey:
    Type: String
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: VPC Details
        Parameters:
          - ProviderVPCCidrBlock
          - ConsumerVPCCidrBlock
          - KeyPair
          - AmazonLinuxAMIVersion
          - CaseId
      -
        Label:
          default: S3 Bucket Details
        Parameters:
          - S3BucketName
          - S3BucketKey
    ParameterLabels:
      ProviderVPCCidrBlock:
        default: CIDR Block for Provider VPC
      ConsumerVPCCidrBlock:
        default: CIDR Block for Consumer VPC
      AmazonLinuxAMIVersion:
        default: Which Amazon Linux Version to Use
      CaseId:
        default: Case ID used to Tag Resources
      S3Bucket:
        default: S3 Bucket for Nested Stack Templates
      S3Key:
        default: S3 Key for Nested Stack Templates

Resources:
  CreateProviderVpcResources:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        ProviderVPCCidrBlock: !Ref 'ProviderVPCCidrBlock'
        CaseId: !Ref 'CaseId'
      TemplateURL: !Sub https://${S3BucketName}.s3.amazonaws.com/${S3BucketKey}/CFN-Template-Kitchen-Sink-Provider-VPC-resources.yaml
  CreateConsumerVpcResources:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        ConsumerVPCCidrBlock: !Ref 'ConsumerVPCCidrBlock'
        CaseId: !Ref 'CaseId'
      TemplateURL: !Sub https://${S3BucketName}.s3.amazonaws.com/${S3BucketKey}/CFN-Template-Kitchen-Sink-Consumer-VPC-resources.yaml
  CreateInstances:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        KeyPair: !Ref 'KeyPair'
        CaseId: !Ref 'CaseId'
        AmazonLinuxAMIVersion: !Ref 'AmazonLinuxAMIVersion'
      TemplateURL: !Sub https://${S3BucketName}.s3.amazonaws.com/${S3BucketKey}/CFN-Template-Kitchen-Sink-instances.yaml
    DependsOn:
      - CreateProviderVpcResources
      - CreateConsumerVpcResources
  CreatePeeringConnection:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        ProviderVPCCidrBlock: !Ref 'ProviderVPCCidrBlock'
        ConsumerVPCCidrBlock: !Ref 'ConsumerVPCCidrBlock'
        CaseId: !Ref 'CaseId'
      TemplateURL: !Sub https://${S3BucketName}.s3.amazonaws.com/${S3BucketKey}/CFN-Template-Kitchen-Sink-VPC-peering.yaml
    DependsOn:
      - CreateProviderVpcResources
      - CreateConsumerVpcResources
  CreateLBs:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        CaseId: !Ref 'CaseId'
      TemplateURL: !Sub https://${S3BucketName}.s3.amazonaws.com/${S3BucketKey}/CFN-Template-Kitchen-Sink-Provider-LBs.yaml
    DependsOn:
      - CreateProviderVpcResources
      - CreateConsumerVpcResources
      - CreateInstances
